/*
 * generated by Xtext
 */
package org.kevoree.modeling;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MetaModelStandaloneSetup extends MetaModelStandaloneSetupGenerated{

	public static void doSetup() {
		new MetaModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

