/*
 * generated by Xtext
 */
package org.kevoree.modeling;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetaModelRuntimeModule extends org.kevoree.modeling.AbstractMetaModelRuntimeModule {

}
