/*
 * generated by Xtext
 */
package org.kevoree.modeling.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MetaModelUiModule extends org.kevoree.modeling.ui.AbstractMetaModelUiModule {
	public MetaModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
