/*
 * generated by Xtext
 */
package org.kevoree.modeling.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.kevoree.modeling.services.MetaModelGrammarAccess;

public class MetaModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MetaModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.kevoree.modeling.parser.antlr.internal.InternalMetaModelParser createParser(XtextTokenStream stream) {
		return new org.kevoree.modeling.parser.antlr.internal.InternalMetaModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MetaModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MetaModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
