/*
 * generated by Xtext
 */
package org.kevoree.modeling.ui.contentassist

import org.kevoree.modeling.ui.contentassist.AbstractMetaModelProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MetaModelProposalProvider extends AbstractMetaModelProposalProvider {
}
