/*
 * generated by Xtext
 */
package org.kevoree.modeling;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MetaModelUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.kevoree.modeling.ui.internal.MetaModelActivator.getInstance().getInjector("org.kevoree.modeling.MetaModel");
	}
	
}
