/*
 * generated by Xtext
 */
package org.kevoree.modeling.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.kevoree.modeling.metaModel.MetaModelPackage;
import org.kevoree.modeling.metaModel.Model;
import org.kevoree.modeling.metaModel.classDeclr;
import org.kevoree.modeling.services.MetaModelGrammarAccess;

@SuppressWarnings("all")
public class MetaModelSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MetaModelGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == MetaModelPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case MetaModelPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case MetaModelPackage.CLASS_DECLR:
				sequence_classDeclr(context, (classDeclr) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (annotations+=annotationDeclr* declarations+=decl*)
	 */
	protected void sequence_Model(EObject context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (annotations+=annotationDeclr* declarations+=classElemDeclr*)
	 */
	protected void sequence_classDeclr(EObject context, classDeclr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
}
