/**
 * generated by Xtext
 */
package org.kevoree.modeling.validation;

import org.kevoree.modeling.validation.AbstractMetaModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MetaModelValidator extends AbstractMetaModelValidator {
}
